### ISSUE TITLE
Cannot style wrapper when invalid input is typed

### ISSUE THREAD

**Issue by pjg** [wojtekmaj/react-date-picker#333]
User can type invalid date into the input field. I'd like to control the styling of the wrapper (`.react-date-picker__wrapper`) whenever such situation occurs. Currently this does not seem to be possible as there's only native `:invalid` pseudo-class on the hidden input, which is insufficient as one cannot style parent depending on the state of the child.

Since there's already `.react-date-picker--open` class added for the opened state, could there be `.react-date-picker--invalid` for the invalid state?

Alternatively, adding support for `onValid` and `onInvalid` hooks would also provide the ability to implement custom styling.

**Comment by wojtekmaj** [comment]
Fixed that in [`make-event-props@1.3.0`](https://github.com/wojtekmaj/make-event-props/releases/tag/v1.3.0). This didn't seem to be a burning issue so we won't create a patch release just to force-bump make-event-props, but if fresh installs or manually installing said dependency should pick the update up.

**Comment by pjg** [comment]
I've upgraded `make-event-props` to v1.3 but that did not solve the issue. The `onInvalid` is never called/activated, despite entering an invalid date part (like `33` for the day field) in the text input. Should I open a new issue for this?

**Comment by wojtekmaj** [comment]
`onInvalid` should be fired but only if you submit the form with an invalid values. Is that the case you have?

**Comment by pjg** [comment]
I see. Yes, I can verify that `onInvalid` is actually being fired/handled by DatePicker on form submit. My use case is very similar to how you add the `:invalid` pseudo class for a single invalid DatePicker input field. I would like to be able to highlight the whole input/date container as being invalid in such situation, something which seems to be impossible currently.

**Comment by wojtekmaj** [comment]
Hmmmm... There is a way to do this in pure CSS, but `:has()` pseudo-class is only supported in Safari 15.4 or later at the moment of writing.

https://codesandbox.io/s/react-date-picker-invalid-styles-ckpnfw

For now, you'll need to use `onInput`/`onChange` to listen for changes, iterate over inputs to check their validity, and change classes accordingly.

**Comment by pjg** [comment]
Thanks for the update! Unfortunately lack of browser support for `:has()` limits its usefulness. I also thought about iterating over all inputs, but that seems a little bit overkill. Ideally `react-date-picker` should bubble up the `invalid` class name to the main container element ;)
